# Generated by Django 3.1.5 on 2021-01-26 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=640)),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_url', models.URLField(blank=True)),
                ('condition', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=8)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.category')),
                ('followed_by', models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishers', to=settings.AUTH_USER_MODEL)),
                ('won_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchasers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
