# Generated by Django 3.1.5 on 2021-01-28 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210126_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='followed_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='won_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchasers', to=settings.AUTH_USER_MODEL),
        ),
    ]
