# Generated by Django 3.1.5 on 2021-01-28 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210128_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='posted_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
