# Generated by Django 3.1.5 on 2021-01-28 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='followed_by',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
