# Generated by Django 3.1.5 on 2021-01-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auction_maxim_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='maxim_bid',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=6),
            preserve_default=False,
        ),
    ]
